#!/bin/bash

BUILD_NUMBER=${BUILD_NUMBER:-last}
BUILD_NUMBER=${TRAVIS_BUILD_NUMBER:-last}
SAUCE_BROWSERS='chrome, firefox'
PERF_RUNS=3
CWD=$(pwd)

RESULT_DIR=results/$BUILD_NUMBER

BROWSERS=$(node -pe "b = 'require('./test/browsers.json').browsers.join(' ')")

echo "Output: $RESULT_DIR"

for browser in $BROWSERS; do
  mkdir -p $RESULT_DIR/$browser
  bro=$(node -pe "b = require('./test/browsers.json')['$browser']; (b & b.name) || '$browser'")
  logo=$(node -pe "b = require('./test/browsers.json')['$browser']; (b & b.logo) || '$browser'")

  node bin/sauce-browsertime data/urls.txt --browser "$bro" -n $PERF_RUNS \
    --output $RESULT_DIR/$browser/metrics.json \
    --reporter spec || exit 1

  echo "... Generate  $RESULT_DIR/$browser/index.html ..."
  node bin/sauce-browsertime-html $RESULT_DIR/$browser/metrics.json -b "$logo" > $RESULT_DIR/$browser/index.html

  echo "... Generate  $RESULT_DIR/$browser.html ..."
  node bin/sauce-browsertime-html $RESULT_DIR/$browser/metrics.json -b "$logo" >  $RESULT_DIR/$browser.html
done

cat > build-index.js << EOF
var fs = require('fs');
var path = require('path');
var browsers = require('./test/browsers');

var args = process.argv.slice(2);

var dir = "$RESULT_DIR";
var index = args[0] === 'index';

if (index) dir = path.join(dir, '..');

var files = fs.readdirSync(dir).filter(function(file) {
  return index ? fs.statSync(path.join(dir, file)).isDirectory() : path.extname(file) === '.html' && file !== 'index.html';
});

var links = index ? files.map(function(file) {
  var link = '<a href="' + file + '">Build #' + file + '</a>';
  return '<p>' + link + '</p>';
}) : files.map(function(file) {
  var b = file.replace('.html', '');
  if (browsers[b]) b = b.logo;
  var img = '<img class="img-thumbnail" src="https://raw.githubusercontent.com/alrra/browser-logos/master/' + b + '/' + b + '_256x256.png" width="256" height="256" alt="' + b + '">';
  return '<a href="' + file + '">' + img + '</a>';
});

var body = [
'<!DOCTYPE html>',
'<html>',
'',
'<head>',
'',
'    <meta charset="utf-8">',
'    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'',
'    <title>' + index ? 'Build list' : 'This page shows raw metrics generated by saucelabs-browsertime for the build $BUILD_NUMBER' + '</title>',
'',
'    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">',
'    <style>',
'    .is-hidden { display: none; }',
'    body { padding: 80px; }',
'    </style>',
'</head>',
'<body>',
links.join('\n'),
index ? '<p>Last build: <a href="$RESULT_DIR">$BUILD_NUMBER</a></p>' : '',
index ? '<p><a href="https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID">Travis Job</a> / <a href="https://s3.amazonaws.com/archive.travis-ci.org/jobs/$TRAVIS_BUILD_ID/log.txt">Logs</a></p>' : '',
'</body>',
'</html>'
];

console.log(body.join('\n'));

EOF

echo "... Generate  $RESULT_DIR/index.html ..."
node build-index.js > $RESULT_DIR/index.html

echo "... Generate  results/index.html ..."
node build-index.js index > results/index.html

echo "... Generate results/last ..."
rm -rf result/last
cp $RESULT_DIR results/last

echo "... Generate index.html ..."
node build-index.js index > index.html

rm build-index.js
