language: node_js
node_js:
  - 0.11
  - 0.10

env:
  global:
    - SAUCE_USERNAME=mklabs
    - secure: "ReXqAX6ZOFkKQIZ73B5y4ZQlXTbjvfZxBP5ryPlSXxAA+EJtSxtOkm4A9p4WzjTxWCcU+qhJWi3WNd7kVuqku+2/N4IKZcVGxgQ+3z45wsLQE7n0vJrQ7dxiwDMhCsJprjG/WCxqdxWRec1EK/a1zVerZAn/rRPlwz01K/7L63M="
