language: node_js
node_js:
  - 0.11
  - 0.10

env:
  global:
    - SAUCE_USERNAME=mklabs
    - secure: "FV+pZI1cjsa7PV+N4sr+VA03CeoqrlGpmvbo2YZ2Wp/eMUFUd+ZdaGic6RUSaLjvAF6aY6RickZ4zWjdYI1A3OXrWcknQzE+u1OQuwOYSb1tqn9aSJm93KFiPSthJetRbrUnXqDkgRELufWU2VeP9ZCx3SgGOXZZypktQCG1E6U="
